name: CI Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensures repo is checked out

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Change to backend directory
        run: cd backend  # If your pom.xml is inside backend/

      - name: Build and Test with Maven
        run: mvn clean test
        working-directory: backend  # Ensure it's in the correct directory
